[package]
name = "sqlparser"
description = "Extensible SQL Lexer and Parser with support for ANSI SQL:2011"
version = "0.5.1-alpha-0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
homepage = "https://github.com/andygrove/sqlparser-rs"
documentation = "https://docs.rs/sqlparser/"
keywords = [ "ansi", "sql", "lexer", "parser" ]
repository = "https://github.com/andygrove/sqlparser-rs"
license = "Apache-2.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2018"

[lib]
name = "sqlparser"
path = "src/lib.rs"

[dependencies]
bigdecimal = { version = "0.1.0", optional = true }
log = "0.4.5"
rowan = "0.10.0"

[dev-dependencies]
simple_logger = "1.0.1"
matches = "0.1"
