[package]
name = "sqlparser_bench"
version = "0.1.0"
authors = ["Dandandan <danielheres@gmail.com>"]
edition = "2018"

[dependencies]
sqlparser = { path = "../" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "sqlparser_bench"
harness = false
